name: network-server
version: '0.0.1'
synopsis: A network server
description: A network server
category: Education
author: Tony Morris <ʇǝu˙sıɹɹoɯʇ@ןןǝʞsɐɥ>
maintainer: Chris Allen <cma@bitemyapp.com>
copyright: Copyright (C) 2013 National ICT Australia Limited 2013
license: BSD3
license-file: etc/LICENCE
homepage: https://github.com/data61/fp-course
git: git@github.com:data61/fp-course.git
bug-reports: https://github.com/data61/fp-course/issues

library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
  - Network.Server.Chat.Chat
  - Network.Server.Chat.Loop
  - Network.Server.Chat
  - Network.Server.Common.Accept
  - Network.Server.Common.Env
  - Network.Server.Common.HandleLens
  - Network.Server.Common.Lens
  - Network.Server.Common.Line
  - Network.Server.Common.Ref
  - Network.Server.Common
  - Network.Server.TicTacToe.Game
  - Network.Server.TicTacToe.Loop
  - Network.Server.TicTacToe
  - Network.Server
  dependencies:
  - base <5 && >=4
  - mtl
  - containers
  - network
  - QuickCheck

executables:
  network-chat:
    main: Chat/Main.hs
    source-dirs: app
    ghc-options: -Wall
    dependencies:
    - base <5 && >=4
    - network-server
    - mtl
    - containers
    - network
    - QuickCheck

  network-tictactoe:
    main: TicTacToe/Main.hs
    source-dirs: app
    ghc-options: -Wall
    dependencies:
    - base <5 && >=4
    - network-server
    - mtl
    - containers
    - network
    - QuickCheck

tests:
  doctests:
    main: doctests.hs

    source-dirs: test

    ghc-options:
    - -Wall
    - -threaded

    dependencies:
    - base <5 && >=3
    - doctest >=0.9.7
    - filepath >=1.3
    - directory >=1.1
    - QuickCheck >=2.0
